export const PROVIDER_BASE_URLS: Record<string, string> = {
  openai: "https://api.openai.com/v1",
  anthropic: "https://api.anthropic.com",
  google: "https://generativelanguage.googleapis.com/v1beta",
  openrouter: "https://openrouter.ai/api/v1",
  groq: "https://api.groq.com/openai/v1",
  deepseek: "https://api.deepseek.com/v1",
  cohere: "https://api.cohere.com/v1",
  together: "https://api.together.xyz/v1",
  ollama: "http://localhost:11434",
  
  minimax: "https://api.minimax.io/anthropic",
  moonshot: "https://api.moonshot.ai/v1",
  "kimi-coding": "https://api.kimi.com/coding/",
  "qwen-portal": "https://portal.qwen.ai/v1",
  "z.ai": "https://api.z.ai/api/paas/v4",
  "z-coding": "https://api.z.ai/api/coding/paas/v4",
  xiaomi: "https://api.xiaomimimo.com/anthropic",
  qianfan: "https://qianfan.baidubce.com/v2",
  modelstudio: "https://coding-intl.dashscope.aliyuncs.com/v1",
  doubao: "https://ark.cn-beijing.volces.com/api/v3",
  byteplus: "https://ark.ap-southeast.bytepluses.com/api/v3",
  
  nvidia: "https://integrate.api.nvidia.com/v1",
  kilocode: "https://api.kilo.ai/api/gateway/",
  synthetic: "https://api.synthetic.new/anthropic",
  venice: "https://api.venice.ai/api/v1",
  huggingface: "https://router.huggingface.co/v1",
  mistral: "https://api.mistral.ai/v1",
  voyage: "https://api.voyageai.com/v1",
  perplexity: "https://api.perplexity.ai",
  "vercel-ai-gateway": "https://ai-gateway.vercel.sh",
};

export const PROVIDER_API_TYPES: Record<string, string> = {
  openai: "openai-completions",
  anthropic: "anthropic-messages",
  google: "google-generative-ai",
  openrouter: "openai-completions",
  groq: "openai-completions",
  deepseek: "openai-completions",
  cohere: "openai-completions",
  together: "openai-completions",
  ollama: "ollama",
  
  minimax: "anthropic-messages",
  moonshot: "openai-completions",
  "kimi-coding": "anthropic-messages",
  "qwen-portal": "openai-completions",
  "z.ai": "openai-completions",
  "z-coding": "openai-completions",
  xiaomi: "anthropic-messages",
  qianfan: "openai-completions",
  modelstudio: "openai-completions",
  doubao: "openai-completions",
  byteplus: "openai-completions",

  nvidia: "openai-completions",
  kilocode: "openai-completions",
  synthetic: "anthropic-messages",
  venice: "openai-completions",
  huggingface: "openai-completions",
  mistral: "openai-completions",
  voyage: "openai-completions",
  perplexity: "openai-completions",
  "vercel-ai-gateway": "openai-completions",
};